"""Deterministic cross-language proof vector (Ed25519 / RFC7638).

The committed JSON is generated by the real signing code; these tests
regenerate it and independently re-check the fingerprint, bhash and signature so
the parent can verify the same bytes with the Go verifier.
"""

import base64
import hashlib
import json
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from backend.tests.proof_vector_builder import build_vector
from device_enrollment.proof import (
    ENROLLMENT_SUBJECT_PREFIX,
    decode_claims,
    decode_header,
    signing_input,
)

VECTOR_PATH = Path(__file__).resolve().parent / "vectors" / "device_proof_vector.json"


def _sha256_b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()


def test_committed_vector_matches_real_signing_code():
    committed = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    assert committed == build_vector()
    assert committed == build_vector()  # deterministic across calls


def test_fingerprint_is_rfc7638_thumbprint():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    x = vector["publicJwk"]["x"]
    canonical = '{"crv":"Ed25519","kty":"OKP","x":"' + x + '"}'
    expected = _sha256_b64url(canonical.encode("utf-8"))
    assert vector["fingerprint"] == expected
    assert vector["operational"]["header"]["kid"] == expected


def test_bhash_is_sha256_of_exact_body():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    for name in ("operational", "enrollment"):
        entry = vector[name]
        expected = _sha256_b64url(entry["body"].encode("utf-8"))
        assert entry["claims"]["bhash"] == expected
        assert entry["claims"]["bhash"] == entry["claims"]["bhash"]


def test_signature_verifies_over_header_payload():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    seed = bytes.fromhex(vector["seedHex"])
    public_key = Ed25519PrivateKey.from_private_bytes(seed).public_key()
    for name in ("operational", "enrollment"):
        token = vector[name]["jws"]
        parts = token.split(".")
        assert len(parts) == 3
        signature = base64.urlsafe_b64decode(parts[2] + "=" * (-len(parts[2]) % 4))
        public_key.verify(signature, signing_input(token))


def test_protected_headers_and_subjects_are_exact():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    operational = vector["operational"]
    enrollment = vector["enrollment"]
    assert set(operational["header"]) == {"alg", "typ", "kid"}
    assert operational["header"]["alg"] == "EdDSA"
    assert operational["header"]["typ"] == "sca-device+jwt"
    assert enrollment["header"]["typ"] == "sca-enrollment+jwt"
    assert enrollment["claims"]["sub"] == (
        ENROLLMENT_SUBJECT_PREFIX + vector["fingerprint"]
    )
    assert operational["claims"]["sub"] == operational["subject"]


def test_claims_types_and_lifetime_are_exact():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    for name in ("operational", "enrollment"):
        entry = vector[name]
        token = entry["jws"]
        assert decode_header(token) == entry["header"]
        assert decode_claims(token) == entry["claims"]
        claims = entry["claims"]
        assert isinstance(claims["iat"], int)
        assert isinstance(claims["exp"], int)
        assert claims["exp"] - claims["iat"] == 60
        assert claims["htm"] == entry["method"]
        assert claims["rt"] == entry["target"]
        assert claims["aud"] == vector["audience"]
        assert len(claims["jti"]) == 22


def test_jws_parts_are_go_canonical_unpadded_base64url():
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    for name in ("operational", "enrollment"):
        for part in vector[name]["jws"].split("."):
            assert "=" not in part
            re_encoded = base64.urlsafe_b64encode(
                base64.urlsafe_b64decode(part + "=" * (-len(part) % 4))
            ).rstrip(b"=")
            assert re_encoded.decode("ascii") == part
