"""Deterministic proof-vector builder used to produce and verify the committed
machine-readable vector under ``device_enrollment/tests/vectors/``.

Everything here is real signing code (``device_enrollment.proof``); nothing is
faked. The seed is a public test-only key so the parent can reproduce the exact
JWS with the Go verifier.
"""

from __future__ import annotations

from typing import Any

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from device_enrollment.proof import (
    DEVICE_TYP,
    ENROLLMENT_SUBJECT_PREFIX,
    ENROLLMENT_TYP,
    build_proof,
    decode_claims,
    decode_header,
    jwk_fingerprint,
    public_jwk,
    serialize_body,
)

TEST_SEED = bytes(range(32))
FIXED_IAT = 1757600000
FIXED_JTI = bytes(range(16))
AUDIENCE = "https://api.example.test/api/v1"
DISPOSITIVO_ID = "11111111-1111-1111-1111-111111111111"
# 43-character case-sensitive unpadded base64url placeholder (test only).
TEST_CODE = "A" * 43
OPERATIONAL_TARGET = "/api/v1/dispositivos/ping"
ENROLLMENT_TARGET = "/api/v1/dispositivos/provision"


def _vector(
    private_key: Ed25519PrivateKey,
    *,
    typ: str,
    target: str,
    payload: dict[str, Any],
    subject: str,
) -> dict[str, Any]:
    body = serialize_body(payload)
    token = build_proof(
        private_key,
        jwk_fingerprint(private_key.public_key()),
        AUDIENCE,
        "POST",
        target,
        body,
        typ,
        subject,
        issued_at=FIXED_IAT,
        lifetime=60,
        jti=FIXED_JTI,
    )
    return {
        "typ": typ,
        "method": "POST",
        "target": target,
        "body": body.decode("utf-8"),
        "subject": subject,
        "header": decode_header(token),
        "claims": decode_claims(token),
        "jws": token,
    }


def build_vector() -> dict[str, Any]:
    private_key = Ed25519PrivateKey.from_private_bytes(TEST_SEED)
    public_key = private_key.public_key()
    fingerprint = jwk_fingerprint(public_key)
    jwk = public_jwk(public_key)
    return {
        "description": (
            "Deterministic Ed25519 DeviceProof vector generated by the real "
            "device_enrollment.proof.build_proof implementation."
        ),
        "note": (
            "Test-only fixed seed. iat is frozen for determinism, so DB-time "
            "admission must be frozen/bypassed when reproducing with the Go "
            "verifier; ValidateClaimsBinding and the signature are time-independent."
        ),
        "seedHex": TEST_SEED.hex(),
        "publicJwk": jwk,
        "fingerprint": fingerprint,
        "audience": AUDIENCE,
        "iat": FIXED_IAT,
        "exp": FIXED_IAT + 60,
        "jti": decode_claims(
            build_proof(
                private_key,
                fingerprint,
                AUDIENCE,
                "POST",
                OPERATIONAL_TARGET,
                serialize_body({"dispositivoId": DISPOSITIVO_ID}),
                DEVICE_TYP,
                DISPOSITIVO_ID,
                issued_at=FIXED_IAT,
                lifetime=60,
                jti=FIXED_JTI,
            )
        )["jti"],
        "operational": _vector(
            private_key,
            typ=DEVICE_TYP,
            target=OPERATIONAL_TARGET,
            payload={"dispositivoId": DISPOSITIVO_ID, "cpuPct": 12.5},
            subject=DISPOSITIVO_ID,
        ),
        "enrollment": _vector(
            private_key,
            typ=ENROLLMENT_TYP,
            target=ENROLLMENT_TARGET,
            payload={"code": TEST_CODE, "publicKey": jwk},
            subject=ENROLLMENT_SUBJECT_PREFIX + fingerprint,
        ),
    }
